[project]
name = "ai-commerce"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.77.0",
    "sentencepiece>=0.2.0",
    "streamlit>=1.45.0",
    "transformers>=4.51.3",
]
